version: '3'
services:
  db_user:
    build: './mysql'
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 1s
      retries: 1
  user_services:
    build: '.'
    ports:
      - "3001:3000"
    depends_on:
      - db_user