version: '3'
services:
  user_db:
    build: './user_services/mysql'
    ports:
      - "3306:3306"

  meeting_db:
    build: './meeting_services/mysql'
    ports:
      - "3307:3306"

  history_db:
    build: './histories/mysql'
    ports:
      - "3308:3306"

  user_services:
    build: './user_services'
    ports:
      - "3000:3000"
    depends_on: 
      - user_db

  meeting_services:
    build: './meeting_services'
    ports:
      - "3001:3000"
    depends_on: 
      - meeting_db

  history_services:
    build: './histories'
    ports:
      - "3002:3000"
    depends_on: 
      - history_db

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_services
      - meeting_services
      - history_services