version: '3'
services:
  db:
    build: './user_services/mysql'
    ports:
      - "3306:3306"

  user_services:
    build: './user_services'
    ports:
      - "3000:3000"
    depends_on: 
      - db

  meeting_services:
    build: './meeting_services'
    ports:
      - "3001:3000"
    depends_on: 
      - db

  history_services:
    build: './histories'
    ports:
      - "3002:3000"
    depends_on: 
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_services
      - meeting_services
      - history_services