version: '3'
services:
  db:
    build: './mysql'
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 1s
      retries: 1
  web:
    build: '.'
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web